package:
  name: neutu-debug
  version: "0.1"

source:
  git_url: https://github.com/janelia-flyem/NeuTu
  git_tag: flyem_release

build:
  number: 6

requirements:
  build:
    - qt-debug      4.8.7
    - libdvid-cpp

  run:
    - qt-debug      4.8.7
    - libdvid-cpp

about:
  home: http://github.com/janelia-flyem/NeuTu
  license: GPL
