#
# This is a conda build config file.
#
# For details on these settings, see:
# https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html
#
# To use this file in conjunction with the 'publish-conda-stack' tool,
# your specs file should start with these lines:
#
#   shared-config:
#     master-conda-build-config: master-conda-build-config.yaml
#
# In general, we should try to keep this in-sync with conda-forge's master build config:
# https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml

boost:
  - 1.70
boost_cpp:
  - 1.70
hdf5:
  - 1.10.5
librdkafka:
  - 1.3.0
lz4_c:
  - 1.8.3
numpy:
  - 1.17
python:
  - 3.7

pin_run_as_build:
  boost:
    max_pin: x.x
  hdf5:
    max_pin: x.x.x
  librdkafka:
    max_pin: x.x.x
  lz4-c:
    max_pin: x.x.x
  numpy:
    max_pin: x.x
  python:
    max_pin: x.x


CONDA_BUILD_SYSROOT:
  # Most conda-forge packages are compatible with MacOSX 10.9,
  # but golang requires at least MacOSX 10.10
  #
  # You will have to install this SDK manually, via this project:
  #
  #   https://github.com/devernay/xcodelegacy
  # 
  # Quick Instructions:
  #
  #   curl https://raw.githubusercontent.com/devernay/xcodelegacy/master/XcodeLegacy.sh > XcodeLegacy.sh
  #   chmod +x XcodeLegacy.sh
  #   sudo ./XcodeLegacy.sh -osx1010 buildpackages
  #   sudo ./XcodeLegacy.sh -osx1010 install
  #
  - /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk
