#
# This is a conda build config file.
#
# For details on these settings, see:
# https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html
#
# To use this file in conjunction with the 'publish-conda-stack' tool,
# your specs file should start with these lines:
#
#   shared-config:
#     master-conda-build-config: master-conda-build-config.yaml
#

boost:
  - 1.70
boost_cpp:
  - 1.70
hdf5:
  - 1.10.5
numpy:
  - 1.17
python:
  - 3.7

pin_run_as_build:
  boost: x.x
  hdf5: x.x.x
  numpy: x.x
  python: x.x


CONDA_BUILD_SYSROOT:
  # Most conda-forge packages are compatible with MacOSX 10.9,
  # but golang requires at least MacOSX 10.10
  #
  # You will have to install this SDK manually, via this project:
  #
  #   https://github.com/devernay/xcodelegacy
  # 
  # Quick Instructions:
  #
  #   curl https://raw.githubusercontent.com/devernay/xcodelegacy/master/XcodeLegacy.sh > XcodeLegacy.sh
  #   chmod +x XcodeLegacy.sh
  #   sudo ./XcodeLegacy.sh -osx1010 install
  #
  - /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk
