{% set version = "3.2.1" %}
{% set sha256 = "ee3ef0e46cb09142ac624852ce070904f469b94c1eb9ec0aa22554439ba4da92" %}

package:
  name: dvid-web-console
  version: {{ version }}

source:
  # Instead of building from source, we download the pre-built release distribution from github
  # (This requires that a dvid-console developer already packaged everything for us...)
  url: https://github.com/janelia-flyem/dvid-console/releases/download/v{{version}}/dvid-console-{{version}}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  
  # Simply copy the bundle files into PREFIX/http/
  script: |
    mkdir -p {{PREFIX}}/http/dvid-web-console
    cp -r * {{PREFIX}}/http/dvid-web-console/

about:
  home: https://github.com/janelia-flyem/dvid-console
  license: BSD 3-Clause
  #license_file: LICENSE.txt # (in the source code, not the release bundle.)
  summary: Web console and API help for DVID
