# Copyright 2014-2019 Peter Williams and collaborators.
# This file is licensed under a 3-clause BSD license; see LICENSE.txt.

{% set name = "gtk+" %}
{% set version = "3.24.9" %}
{% set version_majmin = '.'.join(version.split('.', 2)[:2]) %}
{% set sha256 = "577eb0270d9adf2eb2aa4b03f9c7873fadb20cf265194d0139570f738493e635" %}

package:
  name: gtk3  # note customization
  version: "{{ version }}"

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: http://ftp.gnome.org/pub/gnome/sources/{{ name }}/{{ version_majmin }}/{{ name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}
  patches:
    - m_pi.patch
    - no-module-warning.patch
    - meson-rpaths.patch

build:
  number: 0
  script_env:
    - NJOBS
  run_exports:
    - {{ pin_compatible('gtk3', max_pin='x') }}

requirements:
  build:
    - meson
    - ninja
    - pkg-config
    - pthread-stubs
    - python
    - {{ compiler('c') }}
  host:
    - at-spi2-atk
    - atk
    - cairo {{ cairo }}
    - epoxy 1.*
    - fontconfig {{ fontconfig }}
    - gdk-pixbuf {{ gdk_pixbuf }}
    - glib {{ glib }}
    - gobject-introspection 1.*
    - libxkbcommon 0.8.*
    - pango 1.42.*  # XXX This should be `{{ pango }}`, but pin isn't updated yet
    - wayland 1.*
    - wayland-protocols
    - xorg-inputproto
    - xorg-libice 1.0.*
    - xorg-libsm 1.2.*
    - xorg-libx11 1.6.*
    - xorg-libxcursor 1.2.*
    - xorg-libxi 1.7.*
    - xorg-libxinerama 1.1.*
    - xorg-libxrandr 1.5.*
    - xorg-libxrender 0.9.*
    - xorg-xineramaproto 1.2.*
    - xorg-xproto
  run:
    - gdk-pixbuf {{ gdk_pixbuf }}
    - glib {{ glib }}
    - libxkbcommon 0.8.*
    - pango 1.42.* # {{ pango }}
    - xorg-libice 1.0.*
    - xorg-libsm 1.2.*
    - xorg-libx11 1.6.*
    - xorg-libxcursor 1.2.*
    - xorg-libxi 1.7.*
    - xorg-libxinerama 1.1.*
    - xorg-libxrandr 1.5.*
    - xorg-libxrender 0.9.*

test:
  commands:
    # Check that the binaries can run -- instigated by Meson Linux rpath issues
    # `gtk-builder-tool` and `gtk-query-settings` require a display
    - gtk-encode-symbolic-svg --help
    - gtk-launch --help
    - gtk-query-immodules-3.0
    - gtk-update-icon-cache --help

about:
  home: http://www.gtk.org/
  license: LGPL
  summary: version 3 of the Gtk+ graphical toolkit
