package:
  name: pytiff

  # If we're using a non-tagged revision, append '.postN' to the version
  {% if GIT_DESCRIBE_NUMBER|int %}
  version: {{ GIT_DESCRIBE_TAG }}.post{{ GIT_DESCRIBE_NUMBER }}
  {% else %}
  version: {{ GIT_DESCRIBE_TAG }}
  {% endif %}

source:
  git_url: https://github.com/FZJ-INM1-BDA/pytiff
  git_tag: 0.4.4

build:
  #
  # You must build this recipe using 'conda build --numpy=X.Y'
  #
  number: 1
  string: np{{np}}py{{py}}_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}

requirements:
  build:
    - python {{PY_VER}}*
    - numpy >=1.11,{{NPY_VER}}*
    - cython >=0.23
    - libtiff >=0.4

  run:
    - python {{PY_VER}}*
    - numpy {{NPY_VER}}*
    - libtiff >=0.4

test:
  source_files:
    - pytiff/test
    - test_data
    
  requires:
    - pytest
    - tifffile # This is Christoph Gohlke's 'tifffile' package, installable from the ilastik channel, or from PyPI
    # - hypothesis # We have no conda package for this package, so 'run_test.sh' just installs it with pip 

  imports:
    - pytiff

about:
  home: https://github.com/FZJ-INM1-BDA/pytiff
  license: BSD (3-clause)
  summary: 'Lightweight library for reading chunks from tiff files, including Bigtiff'
