package:
    name: google-api-cpp-client
    version: "0.1"
  
source:
  git_url: https://github.com/google/google-api-cpp-client
  git_branch: master

build:
  number: 2

requirements:
  build:
    - gcc 4.8.5
    - glog
    - jsoncpp 1.6.2
    - gflags
    - curl 7.45*
    - gmock   
    - openssl
 
  run:
    - glog
    - jsoncpp 1.6.2
    - gflags
    - gmock   
    - curl 7.45*
    - libgcc                    4.8.5  19991 # [linux]
    - libgcc                    4.8.5  1     # [osx]
    - openssl

about:
  home: https://github.com/google/google-api-cpp-client 
  license: Apache License
  summary: The core C++ SK for using Google APIs

