{% set version = "1.2.5" %}

package:
  name: draco
  version: "{{ version }}"

source:
  url: https://github.com/google/draco/archive/{{ version }}.tar.gz
  fn:  draco-{{ version }}.tar.gz
  sha256: 76064614bcf5bc80c13291d38c2ea7b8e9c8827a98de93f7bc8bbe4b6e1ec1c4 # 1.2.5
  

build:
  number: 3

requirements:
  build:
    - cmake

test:
  commands:
    - draco_encoder -h
    - draco_decoder -h

about:
  home: https://github.com/google/draco
  license: MIT
  summary: >
    Draco is a library for compressing and decompressing 3D geometric meshes and point clouds.
    It is intended to improve the storage and transmission of 3D graphics.
