{% set version = "1.3.4" %}

package:
  name: draco
  version: "{{ version }}"

source:
  url: https://github.com/google/draco/archive/{{ version }}.tar.gz
  fn:  draco-{{ version }}.tar.gz
  sha256: 9f369ce924974acf9ab582fe8a9e50d86d54346460b0ac6d3808e3fcf269489c # 1.3.4
  

build:
  number: 0

requirements:
  build:
    - cmake

test:
  commands:
    - draco_encoder -h
    - draco_decoder -h

about:
  home: https://github.com/google/draco
  license: MIT
  summary: >
    Draco is a library for compressing and decompressing 3D geometric meshes and point clouds.
    It is intended to improve the storage and transmission of 3D graphics.
