package:
  name: neutu
  version: "0.1"

source:
  git_url: https://github.com/janelia-flyem/NeuTu
  git_tag: flyem_release_stage

build:
  number: 6

requirements:
  build:
    - qt           4.8.7
    - libdvid-cpp

  run:
    - qt           4.8.7
    - libdvid-cpp

about:
  home: http://github.com/janelia-flyem/NeuTu
  license: GPL
