# Set version automatically from the latest tag in git
{% set tagged_version = GIT_DESCRIBE_TAG %}
{% if GIT_DESCRIBE_NUMBER|int != 0 %}
  {% set tagged_version = tagged_version + '.post' + GIT_DESCRIBE_NUMBER %}
{% endif %}

package:
  name: dvid
  version: {{tagged_version}}

source:
  git_url: https://github.com/janelia-flyem/dvid
  git_tag: master

build:
  number: 0
  
  script_env:
    - GOROOT
    - GOPATH

requirements:
  build:
    - go
    - snappy
    - basholeveldb
    - lz4

  run:
    - snappy
    - basholeveldb
    - lz4

about:
  home: http://github.com/janelia-flyem/dvid
  license: BSD
  summary: Distributed, Versioned, Image-oriented Dataservice
