package:
  name: dvid
  version: "0.8.10"

source:
  url: https://github.com/janelia-flyem/dvid/releases/download/v0.8.10/dvid-mac-v0.8.10.tar.gz # [osx]
  md5: b93d66da4aef7e8518a9302dd14d05bc # [osx]
  url: https://github.com/janelia-flyem/dvid/releases/download/v0.8.10/dvid-linux-v0.8.10.tar.gz # [linux]
  md5: a4ff1e9cd5024f9b79140b7e099d1896 # [linux]

build:
  number: 1

requirements:
  build:

  run:
    -snappy

about:
  home: http://github.com/janelia-flyem/dvid
  license: GPL
