package:
  name: dvid
  version: "0.8.12"

source:
  url: https://github.com/janelia-flyem/dvid/releases/download/v0.8.12/dvid-mac-v0.8.12.tar.gz # [osx]
  md5: 8aaa93d52d0a9354b484cd7cd4ad1a4f # [osx]
  url: https://github.com/janelia-flyem/dvid/releases/download/v0.8.12/dvid-linux-v0.8.12.tar.gz # [linux]
  md5: d41d8cd98f00b204e9800998ecf8427e # [linux]

build:
  number: 4

requirements:
  run:
    - snappy

about:
  home: http://github.com/janelia-flyem/dvid
  license: GPL
