package:
  name: dvid
  version: "0.8.11"

source:
  url: https://github.com/janelia-flyem/dvid/releases/download/v0.8.11/dvid-mac-v0.8.11.tar.gz # [osx]
  md5: 7ea061cba0e40d0ae27ce92b5378a4aa # [osx]
  url: https://github.com/janelia-flyem/dvid/releases/download/v0.8.11/dvid-linux-v0.8.11.tar.gz # [linux]
  md5: d170fe3aee617e409bb251b6e9a66014 # [linux]

build:
  number: 3

requirements:
  run:
    - snappy

about:
  home: http://github.com/janelia-flyem/dvid
  license: GPL
