package:
  name: dvid
  version: "0.8.9"

source:
  url: https://github.com/janelia-flyem/dvid/releases/download/v0.8.9/dvid-mac-v0.8.9.tar.gz # [osx]
  md5: e730698b5834e40fa43486200526a3e8 # [osx]
  url: https://github.com/janelia-flyem/dvid/releases/download/v0.8.9/dvid-linux-v0.8.9.tar.gz # [linux]
  md5: f228fd424a708bb76e1d6e4bbe7c6bdf # [linux]

build:
  number: 2

requirements:
  build:

  run:

about:
  home: http://github.com/janelia-flyem/dvid
  license: GPL
