{% set version = "0.8.13" %}

package:
  name: dvid
  version: {{version}}

source:
  url: https://github.com/janelia-flyem/dvid/releases/download/v{{version}}/dvid-mac-v{{version}}.tar.gz # [osx]
  url: https://github.com/janelia-flyem/dvid/releases/download/v{{version}}/dvid-linux-v{{version}}.tar.gz # [linux]

  md5: 579a5a76241a137a160794fb598f6795 # [osx]
  #md5: FIXME # [linux]

build:
  number: 0

requirements:
  run:
    - snappy

about:
  home: http://github.com/janelia-flyem/dvid
  license: GPL
