#
# This is a conda build config file.
#
# For details on these settings, see:
# https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html
#

CONDA_BUILD_SYSROOT:
  # Most conda-forge packages are compatible with MacOSX 10.9,
  # but golang requires at least MacOSX 10.10, so that's what we use.
  #
  # You should install the SDK manually via this project:
  #
  #   https://github.com/devernay/xcodelegacy
  # 
  # Run these commands:
  #
  #   curl https://raw.githubusercontent.com/devernay/xcodelegacy/master/XcodeLegacy.sh > XcodeLegacy.sh
  #   chmod +x XcodeLegacy.sh
  #   sudo ./XcodeLegacy.sh -osx1010 install
  #
  - /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk
