package:
    name: opengm-structured-learning-headers
    version: "2.3.4"

source:
    git_url: https://github.com/opengm/opengm.git
    git_tag: learning-experimental

build:
  number: 5
  string: {{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}

requirements:
  build:
    - gcc 4.8.5 # [unix]
    - boost 1.55.0 # [py2k]
    - boost 1.60.0 # [py3k]
    - python 2.7*|3.5*
    - numpy >=1.9
    - hdf5

about:
    home: https://github.com/opengm/opengm
    license: GNU General Public License (GPL)
    summary: 'A C++ Library for Discrete Graphical Models (This package contains only headers.)'
