package:
  name: jansson
  version: "2.5"

source:
  fn: jansson-2.5.tar.gz
  url: http://www.digip.org/jansson/releases/jansson-2.5.tar.gz
  md5: 46ac93bec48aacf207b67b51c8fbf7f1

build:
  number: 0

# No requirements!


about:
  home: http://www.digip.org/jansson/
  license: HDF5
  license_family: MIT
  license_file: LICENSE
  summary: C library for encoding, decoding and manipulating JSON data.
