package:
  name: dvid-viewer 
  version: "0.1"
  
source:
  git_url: https://github.com/janelia-flyem/libdvid-utils
  git_tag: HEAD

build:
  number: 3
  detect_binary_files_with_prefix: true # (defaults to false)
  
requirements:
  build:
    - gcc 4.8.5 # [linux]
    - gcc 4.8.5 # [osx]
    - boost 1.55.0
    - jsoncpp
    - libdvid-cpp
    - vtk         5.10.1.99
    - qt          4.8.7

    
  run:
    - libgcc
    - boost 1.55.0
    - jsoncpp
    - vtk         5.10.1.99
    - qt          4.8.7
    - libdvid-cpp

about:
  home: http://github.com/janelia-flyem/libdvid-utils
  license: BSD (3-clause)
  summary: Simple C++ viewer for DVID datasets 
