package:
  name: neutu
  version: "0.1"

source:
  git_url: https://github.com/janelia-flyem/NeuTu
  git_branch: flyem_release

build:
  number: 15

requirements:
  build:
    - qt           4.8.7
    - libdvid-cpp 0.2.post55

  run:
    - qt           4.8.7
    - libdvid-cpp 0.2.post55

about:
  home: http://github.com/janelia-flyem/NeuTu
  license: GPL
