{% if not WITH_SOLVERS is defined %}
  {% set WITH_SOLVERS = 1 %}
{% endif %}
{% set WITH_SOLVERS = WITH_SOLVERS|int %}

package:
  {% if WITH_SOLVERS %}
    name: ilastik-versions
  {% else %}
    name: ilastik-versions-no-solvers
  {% endif %}
    version: 1.2

build:
  number: 21 # If you change this, update the ilastik-versions build strings in 'ilastik-everything' recipe requirements

#
# In general, we don't specify exact version requirements in each sub-package.
# But this file tracks the versions of all packages used in the release.
requirements:
  run:
    - ann                       1.1.2     
    #- blist                     1.3.6 # Only needed by deprecated operators     
    - boost                     1.55.0    
    #- cylemon                   1         
    - decorator                 3.4.0
    - dpct                      1.2
    - faulthandler              2.4       
    - fftw                      3.3.4     
    - freetype                  2.5.5     
    - futures                   3.0.2     
    - greenlet                  0.4.6     
    - h5py                      2.7.0     
    - hdf5                      1.8.17
    - hytra                     1.1.4
    - iiboost                   0.2.post5       
    - ilastik-feature-selection 0.123.post9
    - ilastiktools              0.2.post1       
    - ilastikrag                0.1.2
    - itk-seg-conv-only         4.6.1     
    - jbig                      2.1
    - jpeg                      9b        
    - jsonschema                2.4.0     
    - lemon                     1.2.4     
    - libgcc                    4.8.5  19991 # [linux]
    - libgcc                    4.8.5  1     # [osx]
    - libpng                    1.6.27
    - libtiff                   4.0.6
    - libxml2                   2.9.0     
    - mamutexport               0.2.1
    - matplotlib                2.0.0     

{% if WITH_SOLVERS %}
    - multi-hypotheses-tracking-with-gurobi 1.1.3.post1
    - multi-hypotheses-tracking-with-cplex  1.1.3.post1
{% endif %}

    - networkx                  1.11
    - nifty                     0.3b1.post119     py27_0_ge330c2e # [unix]
    
{% if WITH_SOLVERS %}
    ###- nifty-with-cplex          0.2.post173 # [unix] # Not working, apparently.
    - nifty-with-gurobi         0.3b1.post119     py27_0_ge330c2e # [unix]
{% endif %}

    - nose                      1.3.6     
    - numpy                     1.12.1     
    - opengm                    2.3.7.post29     

{% if WITH_SOLVERS %}
    - opengm-with-cplex         2.3.7.post29 # [unix]
{% endif %}

    - openssl                   1.0.2j    
    - pandas                    0.19.2

# {% if WITH_SOLVERS %}
# Only used on windows now!
    # - pgmlink                   1.3.post4       
    # - armadillo                 6.500.5   
    # - dlib                      18.16
    # - mlpack                    1.0.8.99     
    # - opengm-structured-learning-headers  2.3.4 np112py27_3_ga0797cd
# {% endif %}

    - pillow                    4.1.0
    - pip                       6.1.1     
    - psutil                    2.2.1     
    - pyparsing                 2.0.3     
    - pyqt                      4.11.4
    - python                    2.7.12     
    - python-dateutil           2.4.2     
    - pytiff                    0.4.4
    - pytz                      2015.4    
    - qimage2ndarray            1.6       
    - qt                        4.8.7
    - readline                  6.2       
    - requests                  2.13.0
    - scikit-learn              0.18.1    
    - scikit-image              0.12.3
    - scipy                     0.19.0 # [linux]

    # Special build to work-around https://github.com/ContinuumIO/anaconda-issues/issues/899
    - scipy                     0.19.0 np112py27_999_fixed_links # [osx]
    
    - setuptools                23.0.0      
    - sip                       4.16.5    
    - six                       1.9.0     
    - sqlite                    3.13.0
    # - tifffile                  0.9.2.post1 # Can't use the new version. See ilastik-build-conda/tifffile/meta.yaml
    - tifffile                  0.4.post2
    - tk                        8.5.18    
    - vigra                     1.11.0.post222
    - vtk                       5.10.1.99
    - wsdt                      0.2.post9
    - yapsy                     1.10.423  
    - zlib                      1.2.8     
    - xz                        5.2.2

test:
  # Just give SOME test to ensure that the package can be installed at all.
  # (If there are no tests, the test environment isn't even created.)
  imports:
    - vigra
