package:
  name: dlib
  version: "18.16"

source:
  fn: dlib-18.16.tar.bz2
  url: http://downloads.sourceforge.net/project/dclib/dlib/v18.16/dlib-18.16.tar.bz2
  md5: e9e5449bc25370afce2d254327afac99

  patches:
    - CMakeLists.txt.patch   # Add 'install' step
    - CMakeLists.txt.patch_2 # Allow linking external jpeg, even on Mac OSX

build:
  number: 4

requirements:
  build:
    - gcc 4.8.5 # [linux]
    - gcc 4.8.5 # [osx]
    - libpng 1.6.27
    - jpeg
    - sqlite
    - openblas # [linux]

  run:
    - libgcc 4.8.5
    - libpng >=1.6.27,<1.7
    - jpeg
    - sqlite
    - openblas # [linux]

about:
  home: http://dlib.net
  license: Boost
  summary: Dlib is a general purpose cross-platform C++ library designed using contract programming and modern C++ techniques.
    
