package:
  name: python-lz4
  version: !!str 0.7.0

source:
  fn: lz4-0.7.0.tar.gz  
  url: https://pypi.python.org/packages/source/l/lz4/lz4-0.7.0.tar.gz
  md5: e32842a49d5254f6918567197a704492

build:
  number: 1

requirements:
  build:
    - python
    - setuptools
    - nose >=1.0

  run:
    - python
    - nose >=1.0

about:
  home: https://github.com/steeve/python-lz4 
  license: BSD (3-clause)
  summary: 'LZ4 bindings for python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
